### ISSUE TITLE
cannot open files by drag&drop

### ISSUE THREAD

**Issue by christian-rauch** [flathub/net.meshlab.MeshLab#11]
It's not possible to drag a file from the file manager (nautilus) and drop it inside the MeshLab window. 

I only get the message
```
Unable to open file:
"<path>.ply"

Error details: file <path>.ply does not exist.
```
but I am able to open this file just fine from the file manager by double-clicking, pressing enter, etc.

Edit:
I cannot open files by drag&drop from my home folder but I can do so from e.g. `/tmp/<file>.ply`.

**Comment by alemuntoni** [comment]
I can confirm this issue.
It seems that is related with permissions. When running the flatpak with
```
flatpak run --filesystem=host net.meshlab.MeshLab
```
drag&drop works fine. 
@kevinsmia1939 any suggestion on how to solve this?

**Comment by christian-rauch** [comment]
Maybe the permission system does not support drag&drop (yet) because all other ways to open files from within $HOME seem to work.

As a workaround, I think we would only need to add `--filesystem=host` to the build script at: https://github.com/flathub/net.meshlab.MeshLab/blob/master/net.meshlab.MeshLab.yaml. It already contains `--filesystem=/tmp`.

Apart from this, the flatpak is really working awesomely for me compared to my snap experiences in the last ~2 years. Thanks @kevinsmia1939 .

**Comment by christian-rauch** [comment]
I created PR https://github.com/flathub/net.meshlab.MeshLab/pull/13 to add this permission and the CI already created a new flatpak with this change. It can be tested with `flatpak install --user https://dl.flathub.org/build-repo/54458/net.meshlab.MeshLab.flatpakref` and drag&drop now works as expected for me with this.

**Comment by kevinsmia1939** [comment]
Hi,
@christian-rauch 
Normally, giving  the access to host is a bad practice since it just give the app all the system and user files. 
I have seen the discussion here https://github.com/flathub/org.atheme.audacious/issues/5
However, I to like convenience, I will look into it further.

**Comment by christian-rauch** [comment]
Fixed by https://github.com/flathub/net.meshlab.MeshLab/pull/13.
