### ISSUE TITLE
Tries to save to unwritable directory by default

### ISSUE THREAD

**Issue by simonschmeisser** [flathub/net.meshlab.MeshLab#3]
When I open a STL file by clicking on it in Dolphin (file manager) and then go for File > "Save Mesh as ..." the default directory is `/run/user/1000/doc/somehash123/`. This is not writable by the user and meshlab then hangs.
![grafik](https://user-images.githubusercontent.com/372442/125086698-28f49580-e0cc-11eb-9d6f-652e48638039.png)

The dialog should end up in the folder containing the file

**Comment by kevinsmia1939** [comment]
I see that you post the question in meshlab github page as well, but since the upstream dev fix this, and probably be in the next release, I will close this for now.
