### ISSUE TITLE
include meshlabserver

### ISSUE THREAD

**Issue by simonschmeisser** [flathub/net.meshlab.MeshLab#4]
`meshlabserver` is a separate binary for batch processing meshes. I think it's not included but maybe I just don't use the right commands to run it?

**Comment by alemuntoni** [comment]
meshlabserver has been dismissed in favour of [PyMeshLab](https://pymeshlab.readthedocs.io/en/latest/).
https://github.com/cnr-isti-vclab/meshlab/issues/911

**Comment by simonschmeisser** [comment]
Oh, thanks for the hint. That looks a lot nicer indeed!
