### ISSUE TITLE
MeshLab is using EOL'd runtime

### ISSUE THREAD

**Issue by neildarlow** [flathub/net.meshlab.MeshLab#85]
Hi,

Can this application be updated to use the 5.15-23.08 KDE Platform and Sdk please? The current 5.15-22.08 is EOL.

Regards,
Neil Darlow

**Comment by kevinsmia1939** [comment]
Fix in https://github.com/flathub/net.meshlab.MeshLab/pull/86

**Comment by neildarlow** [comment]
Thank you. I'll close.
